version: '3'
services:
  php:
    build: .
    image: php:8.1-apache
    volumes:
      - ./app:/var/www/html
    networks:
      - mynetwork
    ports:
      - 8000:80
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_project_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - 9906:3306
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - 8080:80
    networks:
      - mynetwork
networks:
  mynetwork:
